LCLFileUpload/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rebex.Net;
using DevExpress.Web.Mvc;
using LCLFileUpload.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.UI.WebControls;
using System.Xml;
using WebMatrix.WebData;
using System.Configuration;
using System.IO;

namespace LCLFileUpload.Controllers
{
    public class DataController : Controller
    {
        LCLFileUpload.Models.WEBWISDOMEntities db = new LCLFileUpload.Models.WEBWISDOMEntities();
        LCLFileUpload.DAL.Dal dal = new LCLFileUpload.DAL.Dal();

        //
        // GET: /Data/

        public ActionResult TagRanges()
        {
            if (!WebSecurity.Initialized)
            {
                try
                {
                    WebSecurity.InitializeDatabaseConnection(ConfigurationManager.ConnectionStrings["WEBWISDOMConnection"].ConnectionString, "System.Data.SqlClient", "tblUserInfo", "LoginID", "UserName", autoCreateTables: true);
                }
                catch { }
            }
            var f = new JobListforDLPM();
            f.JobList = dal.GetListOfJobsForDLPM(WebSecurity.CurrentUserId);
            return View(f); 
        }

        public ActionResult DownloadData()
        {
            if (!WebSecurity.Initialized)
            {
                try
                {
                    WebSecurity.InitializeDatabaseConnection(ConfigurationManager.ConnectionStrings["WEBWISDOMConnection"].ConnectionString, "System.Data.SqlClient", "tblUserInfo", "LoginID", "UserName", autoCreateTables: true);
                }
                catch { }
            }
            var f = new JobListforDLPM();
            f.JobList = dal.GetListOfJobsForDLPM(WebSecurity.CurrentUserId);
            return View(f);
        }

        [HttpPost]
        public ActionResult DownloadData(HttpPostedFileBase[] files)
        {
            try
            {
                Sftp client = new Sftp();

                string hostname = System.Configuration.ConfigurationManager.AppSettings["hostname"];
                string userName = System.Configuration.ConfigurationManager.AppSettings["username"].ToString();
                string password = System.Configuration.ConfigurationManager.AppSettings["password"].ToString();
                client.Connect(hostname);
                client.Login(userName, password);
                client.ChangeDirectory("TerminalFiles");

                /*Lopp for multiple files*/
                foreach (HttpPostedFileBase file in files)
                {
                    /*Geting the file name*/

                    string filename = System.IO.Path.GetFileName(file.FileName);
                    string fileContentType = file.ContentType;
                    byte[] fileBytes = new byte[file.ContentLength];
                    file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));
                    System.IO.MemoryStream ms = new System.IO.MemoryStream(fileBytes, 0, Convert.ToInt32(file.ContentLength));
                    client.PutFile(ms, filename);
                }
                client.Disconnect();
                ViewBag.Message = "File Uploaded successfully.";
            }
            catch
            {
                ViewBag.Message = "Error while uploading the files.";
            }
            return View(); return RedirectToAction("Index");
        }

        [ValidateInput(false)]
        public ActionResult _grdEnterTagRanges(int jobNo)
        {
            int RentalID = dal.GetRentalID(jobNo);
            var model = db.tblRentalTagRanges;
/*            if (model.Count() > 0) 
                return PartialView("_grdEnterTagRanges", model.ToList().Where(t => !(t.Deleted)));
            else
            {
                var f = new tblRentalTagRange();
                f.RentalID = RentalID;
                return PartialView(f);
            } */
                        return PartialView("_grdEnterTagRanges", model.ToList().Where(t => !(t.Deleted) && (t.RentalID == RentalID)));
        }

        [ValidateInput(false)]
        public ActionResult EnterTagRanges(int jobNo)
        {
            return View();
//            int RentalID = dal.GetRentalID(jobNo);
  //          var model = db.tblRentalTagRanges;
            //            return PartialView("_grdEnterTagRanges", model.ToList().Where(t => !(t.Deleted) && (t.RentalID == RentalID)));
    //        return PartialView("_grdEnterTagRanges", model.ToList());
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult _grdEnterTagRanges([ModelBinder(typeof(DevExpressEditorsBinder))] LCLFileUpload.Models.tblRentalTagRange item)
        {
            var model = db.tblRentalTagRanges;
//            var f = new tblRentalTagRange();
            if (ModelState.IsValid) dal.AddTagRange(item.RentalID, item.TagValFrom, item.TagValTo, item.Description);
            return PartialView("_grdEnterTagRanges", model.ToList().Where(t => !(t.Deleted) && (t.RentalID == item.RentalID)));
//            return PartialView("_grdEnterTagRanges", model.ToList());
        }

        [ValidateInput(false)]
        public ActionResult _ListTagRangesPartial(int jobNo)
        {
            int RentalID = dal.GetRentalID(jobNo);

            var model = db.tblRentalTagRanges;
            return PartialView(model.ToList().Where(t => !(t.Deleted) && (t.RentalID == RentalID)));
        }

        [ValidateInput(false)]
        public ActionResult _EnterTagRangesPartial(int jobNo)
        {
            int RentalID = dal.GetRentalID(jobNo);
            Int32 tempvalue = 0;
            ViewData["TagRangeID"] = tempvalue.ToString();
            var f = new tblRentalTagRange();
            f.RentalID = RentalID;
            return PartialView(f);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult _EnterTagRangesPartial(tblRentalTagRange tblrentalragrange)
        {
            if (ModelState.IsValid)
            {
                if (tblrentalragrange.TagValTo >= tblrentalragrange.TagValFrom)
                {
                    if (dal.FindIfTagRangeOverlap(tblrentalragrange.RentalID, tblrentalragrange.TagValFrom, tblrentalragrange.TagValTo, tblrentalragrange.Description).Rows.Count == 0)
                    {
                        dal.AddTagRange(tblrentalragrange.RentalID, tblrentalragrange.TagValFrom, tblrentalragrange.TagValTo, tblrentalragrange.Description);
                        ModelState.Clear();
                    }
                    else
                    {
                        ViewBag.Message = "ERROR: Tag Range or Description already exist, Please try again.";
                    }
                }
                else
                {
                    ViewBag.Message = "ERROR: Tag Range value 'To' is less than 'From', Please try again.";
                }
            }
            Int32 tempvalue = 0;
            ViewData["TagRangeID"] = tempvalue.ToString();
            var f = new tblRentalTagRange();
            f.RentalID = tblrentalragrange.RentalID;
            return PartialView(f);
        }

        [ValidateInput(false)]
        public ActionResult _EditTagRange(int JobNo, int TagRangeID)
        {
            tblRentalTagRange tblrentaltagrange = db.tblRentalTagRanges.Find(TagRangeID);
            return View(tblrentaltagrange);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult _EditTagRange(int JobNo, tblRentalTagRange tblrentalragrange)
        {
            if (tblrentalragrange.TagValTo >= tblrentalragrange.TagValFrom)
            {
                if (dal.FindIfTagRangeOverlapForEdit(tblrentalragrange.TagRangeID, tblrentalragrange.RentalID, tblrentalragrange.TagValFrom, tblrentalragrange.TagValTo, tblrentalragrange.Description).Rows.Count == 0)
                {
                    dal.EditTagRange(tblrentalragrange.TagRangeID, tblrentalragrange.TagValFrom, tblrentalragrange.TagValTo, tblrentalragrange.Description);
                    return RedirectToAction("EnterTagRanges", new { JobNo = JobNo });
                }
                else
                {
                    ViewBag.Message = "ERROR: Tag Range or Description already exist, Please try again.";
                }
            }
            else
            {
                ViewBag.Message = "ERROR: Tag Range value 'To' is less than 'From', Please try again.";
            }
            tblRentalTagRange tblrentaltagrange = db.tblRentalTagRanges.Find(tblrentalragrange.TagRangeID);
            return View(tblrentaltagrange);
        }

        [ValidateInput(false)]
        public ActionResult _DeleteTagRange(int JobNo, int TagRangeID)
        {
            tblRentalTagRange tblrentaltagrange = db.tblRentalTagRanges.Find(TagRangeID);
            return View(tblrentaltagrange);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult _DeleteTagRange(int JobNo, tblRentalTagRange tblrentalragrange)
        {
            dal.DeleteTagRange(tblrentalragrange.TagRangeID);
            return RedirectToAction("EnterTagRanges", new { JobNo = JobNo });
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult _grdNewEnterTagRanges([ModelBinder(typeof(DevExpressEditorsBinder))] LCLFileUpload.Models.tblRentalTagRange item)
        {
            var model = db.tblRentalTagRanges;
            var f = new tblRentalTagRange(); 
            return PartialView(f);
        }
         
        [ValidateInput(false)]
        public ActionResult _UploadFilesPartial(int JobNo)
        {
            Sftp client = new Sftp();
            string hostname = System.Configuration.ConfigurationManager.AppSettings["hostname"];
            string userName = System.Configuration.ConfigurationManager.AppSettings["username"].ToString();

LCLFileUpload/Views/Data/ConfirmJob.cshtml
@{
    ViewBag.Title = "Confirm Job";
}

<h3>@ViewBag.Title</h3>
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />

<h4> @ViewBag.Message</h4>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <p>
            <input type="submit" value="Confirm" />
        </p>
    </fieldset>
}
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />
<br />
<div>
    @Html.ActionLink("Back to List", "EnterTagRanges", new { JobNo = Request.Params["JobNo"] })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LCLFileUpload/Views/Data/Conformation.cshtml
@model LCLFileUpload.Models.JobListforDLPM


@{
    ViewBag.Title = "List Of Jobs - Confirmation";
}

<h3>List Of Jobs - Confirmation</h3>
<br />
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />
<table>
    <tr>
    @foreach (System.Data.DataColumn Col in Model.JobList.Columns)
        {
            <th>
                    @if (@Col.ColumnName != "Select")
                    {
                        <h7>@Col.ColumnName </h7>}
                    else {}
            </th>
            <td>
            </td>
    }
    </tr>
    <tbody>
    @foreach (System.Data.DataRow Row in Model.JobList.Rows)
    {
        <tr>
            @for (int i = 0; i <= Model.JobList.Columns.Count - 1; i++)
            {
                  <td>
                    @if (Model.JobList.Columns[i].ColumnName != "Select")
                    {
                        <h6>@Row[i].ToString()</h6>
                    }
                    else
                    {
                        <h5>@Html.ActionLink("Confirm", "ConfirmJob", new { JobNo = @Row[i].ToString().Trim() })</h5>
                        <h5>@Html.ActionLink("Add Notes", "AddNotes", new { JobNo = @Row[i].ToString().Trim() })</h5>
                    }   
                  </td>
                
                <td> @ViewBag.Message</td>
            }
        </tr>
    }
    </tbody>
</table>

LCLFileUpload/Views/Data/DownloadData.cshtml
@model LCLFileUpload.Models.JobListforDLPM


@{
    ViewBag.Title = "List Of Jobs - Upload Data";
}

<h3>List Of Jobs - Upload Data</h3>
<br />
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />
<table>
    <tr>
    @foreach (System.Data.DataColumn Col in Model.JobList.Columns)
        {
            <th>
                    @if (@Col.ColumnName != "Select")
                    {
                        <h7>@Col.ColumnName </h7>}
                    else {}
            </th>
            <td>
            </td>
    }
    </tr>
    <tbody>
    @foreach (System.Data.DataRow Row in Model.JobList.Rows)
    {
        <tr>
            @for (int i = 0; i <= Model.JobList.Columns.Count - 1; i++)
            {
                  <td>
                    @if (Model.JobList.Columns[i].ColumnName != "Select")
                    {
                        <h6>@Row[i].ToString()</h6>
                    }
                    else
                    {
                        <h5>@Html.ActionLink("Select", "UploadFiles", new { jobNo = @Row[i].ToString().Trim() })</h5>
                    }   
                        </td>
                <td></td>
            }
        </tr>
    }
    </tbody>
</table>

LCLFileUpload/Views/Data/EnterTagRanges.cshtml
@{
    ViewBag.Title = "Enter Tag Ranges";
}
<section id="TagRangeForm">
    @{Html.RenderAction("_EnterTagRangesPartial");}
    @{Html.RenderAction("_ListTagRangesPartial");}
</section>

LCLFileUpload/Views/Data/TagRanges.cshtml
@model LCLFileUpload.Models.JobListforDLPM


@{
    ViewBag.Title = "List Of Jobs - Tag Ranges";
}

<h3>List Of Jobs - Tag Ranges</h3>
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />
<table>
    <tr>
    @foreach (System.Data.DataColumn Col in Model.JobList.Columns)
        {
            <th>
                    @if (@Col.ColumnName != "Select")
                    {
                        <h7>@Col.ColumnName </h7>}
                    else {}
            </th>
            <td>
            </td>
    }
    </tr>
    <tbody>
    @foreach (System.Data.DataRow Row in Model.JobList.Rows)
    {
        <tr>
            @for (int i = 0; i <= Model.JobList.Columns.Count - 1; i++)
            {
                  <td>
                    @if (Model.JobList.Columns[i].ColumnName != "Select")
                    {
                       <h6> @Row[i].ToString()</h6>
                    }
                    else
                    {
                        <h5>@Html.ActionLink("Select", "EnterTagRanges", new { jobNo = @Row[i].ToString().Trim() })</h5>
                    }   
                        </td>
                <td></td>
            }
        </tr>
    }
    </tbody>
</table>

LCLFileUpload/Views/Data/UploadFiles.cshtml
@{
    ViewBag.Title = "Upload Terminal Files";
}
<section id="UploadFilesForm">
    <h3>@ViewBag.Message</h3>
    @{Html.RenderAction("_UploadFilesPartial");}
    @{Html.RenderAction("_ListUploadedFilesErrorsPartial");}
    @{Html.RenderAction("_ListUploadedFilesPartial");}

</section>

LCLFileUpload/Views/Data/_DeleteTagRange.cshtml
@model LCLFileUpload.Models.tblRentalTagRange

@{
    ViewBag.Title = "Delete Tag Range";
}

<h3>@ViewBag.Title</h3>
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>tblOffice</legend>

        <!--<div class="editor-label">
            @Html.LabelFor(model => model.RentalID)
        </div>-->
        <div class="editor-field">
            @Html.EditorFor(model => model.RentalID)
            @Html.ValidationMessageFor(model => model.RentalID)
        </div>
        <div class="editor-field" >
            <h7>@Html.LabelFor(model => model.TagValFrom)</h7>
        </div>
        <div class="editor-field" >
            @Html.EditorFor(model => model.TagValFrom)
            @Html.ValidationMessageFor(model => model.TagValFrom)
        </div>       
        <div class="editor-field" >
            <h7>@Html.LabelFor(model => model.TagValTo)</h7>
        </div>
        <div class="editor-field" >
            @Html.EditorFor(model => model.TagValTo)
        </div>       
        <div class="editor-field" >
            <h7>@Html.LabelFor(model => model.Description)</h7>
        </div>
        <div class="editor-field" >
            @Html.EditorFor(model => model.Description)
        </div>       
        <p>
            <input type="submit" value="Delete" />
        </p>
    </fieldset>
}
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />
<h8> @ViewBag.Message</h8>
<br />
<div>
    <h5>@Html.ActionLink("Back to List", "EnterTagRanges", new { JobNo = Request.Params["JobNo"] })</h5>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LCLFileUpload/Views/Data/_DownloadDataPartial.cshtml
<section id="DownloadDataForm">
    @{Html.RenderAction("_UploadFilesPartial");}
</section>

LCLFileUpload/Views/Data/_EditTagRange.cshtml
@model LCLFileUpload.Models.tblRentalTagRange

@{
    ViewBag.Title = "Edit Tag Range";
}

<h3>@ViewBag.Title</h3>
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>tblOffice</legend>

        <!--<div class="editor-label">
            @Html.LabelFor(model => model.RentalID)
        </div>-->
        <div class="editor-field">
            @Html.EditorFor(model => model.RentalID)
            @Html.ValidationMessageFor(model => model.RentalID)
        </div>
        <div class="editor-field" >
            <h7>@Html.LabelFor(model => model.TagValFrom)</h7>
        </div>
        <div class="editor-field" >
            @Html.EditorFor(model => model.TagValFrom)
            @Html.ValidationMessageFor(model => model.TagValFrom)
        </div>       
        <div class="editor-field" >
            <h7>@Html.LabelFor(model => model.TagValTo)</h7>
        </div>
        <div class="editor-field" >
            @Html.EditorFor(model => model.TagValTo)
        </div>       
        <div class="editor-field" >
            <h7>@Html.LabelFor(model => model.Description)</h7>
        </div>
        <div class="editor-field" >
            @Html.EditorFor(model => model.Description)
        </div>       
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />
<h4> @ViewBag.Message</h4>
<br />
<div>
    <h5>@Html.ActionLink("Back to List", "EnterTagRanges", new { JobNo = Request.Params["JobNo"] })</h5>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LCLFileUpload/Views/Data/_EnterTagRangesPartial.cshtml
@model LCLFileUpload.Models.tblRentalTagRange
@{
    Layout = null;
}
@{
    ViewBag.Title = "Enter Tag Ranges";
}

<h3>Enter Tag Ranges</h3>
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />
<br />
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>tblExpenseDetail</legend>
   
        <div class="editor-field">
            @Html.TextBox("TagRangeID",ViewData["TagRangeID"],new { style = "display: none;" })
            @Html.ValidationMessageFor(model => model.TagRangeID)
        </div>
        <div class="editor-field">
            @Html.TextBox("RentalID",ViewData["RentalID"],new { style = "display: none;" })
            @Html.ValidationMessageFor(model => model.TagRangeID)
        </div>
        <div class="editor-label">
            <h7>@Html.Label("Tag Value From")</h7>
        </div>
        <div class="editor-field">
            @Html.TextBox("TagValFrom")
            @Html.ValidationMessageFor(model => model.TagValFrom)
        </div>
        <div class="editor-label">
            <h7>@Html.Label("Tag Value To")</h7>
        </div>
        <div class="editor-field">
            @Html.TextBox("TagValTo")
            @Html.ValidationMessageFor(model => model.TagValTo)
        </div>
        <div class="editor-label">
            <h7>@Html.Label("Tag Description")</h7>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
        <h4> @ViewBag.Message</h4>

    </fieldset>
}
       
<div>
  <!--  @Html.ActionLink("Show The Crystal", "ShowReport") -->
</div>

LCLFileUpload/Views/Data/_ListUploadedFilesErrorsPartial.cshtml
@model LCLFileUpload.Models.ListOfUploadedFilesErrors
@{
    Layout = null;
}

@{
    ViewBag.Title = "Invalid Uploaded Files";
}

<h3>Invalid Uploaded Files</h3>
<hr style="color:#c00;background-color:#c00;height:1px;border:none;" />
<table>
    <tr>
    @foreach (System.Data.DataColumn Col in Model.ErrorList.Columns)
        {
            <th>
                    @if (@Col.ColumnName != "Select")
                    {
                        <h7>@Col.ColumnName </h7>}
                    else {}
            </th>
            <td>
            </td>
    }
    </tr>
    <tbody>
    @foreach (System.Data.DataRow Row in Model.ErrorList.Rows)
    {
        <tr>
            @for (int i = 0; i <= Model.ErrorList.Columns.Count - 1; i++)
            {
                  <td>
                    @if (Model.ErrorList.Columns[i].ColumnName != "Select")
                    {
                        <h6>@Row[i].ToString()</h6>
                    }
                        </td>
                <td></td>
            }
        </tr>
    }
    </tbody>
</table>

LCLFileUpload/Views/Data/_UploadFilesPartial.cshtml
@{
    Layout = null;
}
@{
    ViewBag.Title = "Upload Terminal Files";
}
<hgroup class="title">
    <h3>@ViewBag.Title</h3>
    <h3>@ViewBag.Message</h3>
    <hr style="color:#c00;background-color:#c00;height:1px;border:none;" />

</hgroup>

@using (Html.BeginForm("UploadFiles", "Data", new { JobNo = Request.Params["JobNo"] }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset >

    <!-- <div style="color:Red;font-size:20px">@ViewBag.Message</div>-->
        <h4>@ViewBag.Message</h4>
    <input type="file" name="files" value="" multiple="multiple"/>
    <input type="submit" id="saveButton" value="Upload Terminal Files"  title="Uplad"/>
    </fieldset>
}

LCLFileUpload/Views/Data/_grdEnterTagRanges.cshtml
@model IEnumerable<LCLFileUpload.Models.tblRentalTagRange>
@{
//    ViewBag.TitleStyleClass = "About";
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "grdEnterTagRanges";
        settings.KeyFieldName = "TagRangeID";
        settings.CallbackRouteValues = new { Controller = "Data", Action = "_grdEnterTagRanges", JobNo = Request.Params["JobNo"] };
        settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        settings.Theme = "BlackGlass";
        
        settings.SettingsPager.PageSize = 20;
        settings.Settings.VerticalScrollBarMode = ScrollBarMode.Visible;
        settings.Settings.VerticalScrollableHeight = 500;
        settings.Settings.VerticalScrollBarStyle = GridViewVerticalScrollBarStyle.Virtual;
        settings.ControlStyle.Paddings.Padding = System.Web.UI.WebControls.Unit.Pixel(0);
        settings.ControlStyle.Border.BorderWidth = System.Web.UI.WebControls.Unit.Pixel(0);
        settings.ControlStyle.BorderBottom.BorderWidth = System.Web.UI.WebControls.Unit.Pixel(1);
//        settings.SettingsPopup.EditForm.Width = 600;

        settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "Data", Action = "_grdEnterTagRanges", JobNo = Request.Params["JobNo"] };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "Data", Action = "_grdEnterTagRanges", JobNo = Request.Params["JobNo"] };
        //    settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "EnterExpenses", Action = "_grdEditTravelLogUpdate", employeeno = Request.Params["EmployeeNo"] };
        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = false;

        settings.CommandColumn.Visible = true;
        settings.CommandColumn.NewButton.Visible = true;
        settings.CommandColumn.DeleteButton.Visible = false;
        settings.CommandColumn.DeleteButton.Text = "Delete";
        settings.CommandColumn.EditButton.Visible = true;
        settings.SettingsPager.Visible = false;
        settings.Settings.ShowGroupPanel = false;
        settings.Settings.ShowFilterRow = false;
        settings.Settings.ShowFilterRowMenu = false; 
        
        settings.SettingsBehavior.AllowSelectByRowClick = true;
        settings.CommandColumn.ShowSelectCheckbox = false;
        settings.SettingsDetail.AllowOnlyOneMasterRowExpanded = false;
        settings.SettingsDetail.ShowDetailRow = false;

        settings.Columns.Add("TagValFrom").Width = System.Web.UI.WebControls.Unit.Percentage(20);
        settings.Columns.Add("TagValTo").Width = System.Web.UI.WebControls.Unit.Percentage(20);
        settings.Columns.Add("Description").Width = System.Web.UI.WebControls.Unit.Percentage(10);
        //        settings.Columns.Add("NormalCommute").Width = System.Web.UI.WebControls.Unit.Percentage(10);
        //        settings.Columns.Add("IOCode",MVCxGridViewColumnType.CheckBox).Width = System.Web.UI.WebControls.Unit.Percentage(7);
//        settings.Columns.Add("Status").Width = System.Web.UI.WebControls.Unit.Percentage(5);
//        settings.Columns.Add("Comments").Width = System.Web.UI.WebControls.Unit.Percentage(20);

//        settings.SetDetailRowTemplateContent(c =>
  //      {
    //        Html.RenderAction("_grdAuditIOCashExpenses", new { DetailID = DataBinder.Eval(c.DataItem, "DetailID") });
      //  });
    });
    if (ViewData["EditError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()

LCLFileUpload/Views/Data/_grdEnterTagRangesOld.cshtml
@{
    var grid = Html.DevExpress().GridView(
        settings => {
            settings.Name = "grdEnterTagRanges";
            settings.KeyFieldName = "TagRangeID";
            settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
            settings.Theme = "BlackGlass";

            settings.SettingsPager.PageSize = 20;
            settings.Settings.VerticalScrollBarMode = ScrollBarMode.Visible;
            settings.Settings.VerticalScrollableHeight = 500;
            settings.Settings.VerticalScrollBarStyle = GridViewVerticalScrollBarStyle.Virtual;
            settings.ControlStyle.Paddings.Padding = System.Web.UI.WebControls.Unit.Pixel(0);
            settings.ControlStyle.Border.BorderWidth = System.Web.UI.WebControls.Unit.Pixel(0);
            settings.ControlStyle.BorderBottom.BorderWidth = System.Web.UI.WebControls.Unit.Pixel(1); 
            
            settings.CallbackRouteValues = new { Controller = "Data", Action = "_grdEnterTagRanges" };
            settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "Data", Action = "_grdNewEnterTagRanges" };
            settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "Data", Action = "_grdEnterTagRanges" };
            settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "Data", Action = "_grdEnterTagRanges" };
            settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;

            settings.CommandColumn.Visible = true;
            settings.CommandColumn.NewButton.Visible = true;
            settings.CommandColumn.DeleteButton.Visible = true;
            settings.CommandColumn.EditButton.Visible = true;


            settings.Columns.Add("TagValFrom", MVCxGridViewColumnType.TextBox);
            settings.Columns.Add("TagValTo", MVCxGridViewColumnType.TextBox);
            settings.Columns.Add("Description", MVCxGridViewColumnType.TextBox);

            settings.PreRender = (sender, e) => {
                ((MVCxGridView)sender).StartEdit(1);
            };
        });

    if (ViewData["EditError"] != null) {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()